<?php
$this->title = "Delete album";
$this->headTitle($this->title);
?>

<p>Are you sure that you want to delete 
    '<?php echo $this->escape($this->album['title']); ?>' by 
    '<?php echo $this->escape($this->album['artist']); ?>'?
</p>
<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo $this->album['id']; ?>" />
        <button type="submit" class="btn btn-success" name="del" value="Yes"><i class="icon-ok icon-white"></i> Yes</button>
        <button type="submit" class="btn btn-danger" name="del" value="No"><i class="icon-remove icon-white"></i> No</button>
    </div>
</form>