<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>

<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Artist</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->albums as $album) : ?>
            <tr>
                <td><?php echo $this->escape($album->id); ?></td>
                <td><?php echo $this->escape($album->title); ?></td>
                <td><?php echo $this->escape($album->artist); ?></td>
                <td>
                    <a class="btn btn-success" href="<?php
                    echo $this->url(array('controller' => 'index',
                        'action' => 'edit', 'id' => $album->id));
                    ?>"><i class="icon-edit icon-white"></i> Edit</a>
                </td>
                <td>
                    <a class="btn btn-danger" href="<?php
                    echo $this->url(array('controller' => 'index',
                        'action' => 'delete', 'id' => $album->id));
                    ?>"><i class="icon-remove icon-white"></i> Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>