<?php
//$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Framework Tutorial');
//echo $this->doctype();
?>

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(); ?>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Ubuntu orange and unique font.">
        <meta name="author" content="Thomas Park">
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css'); ?>
    </head>

    <body style="padding-top: 50px;" data-offset="80">

        <!-- Navbar
  ================================================== -->
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/">Zend Framework 1 and Twitter Bootstrap 2 Demo</a>
                    <div class="nav-collapse collapse" id="main-menu">
                        <ul class="nav" id="main-menu-left">
                            <li><a href="<?php
                                echo $this->url(array('controller' => 'index',
                                    'action' => 'add'));
                                ?>">Add new album</a>
                            </li>
                            <li><a href="<?php
                                echo $this->url(array('controller' => 'index',
                                    'action' => 'index'));
                                ?>">List albums</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <h1><?php echo $this->escape($this->title); ?></h1>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>